#!/usr/bin/env bash
# One-shot setup for an Oracle Cloud Always Free ARM VM (Ubuntu 22.04/24.04).
#
# Run ON THE VM, from the repository root:
#   git clone https://github.com/<user>/ai-data-scientist.git
#   cd ai-data-scientist
#   ./deploy/oracle/setup.sh
#
# Installs Docker, fixes the two firewall layers Oracle images ship with,
# writes deploy/oracle/.env, then builds and starts the stack behind Caddy.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/deploy/oracle"
ENV_FILE="$HERE/.env"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -ne 0 ] || die "Run as the normal 'ubuntu' user, not root (sudo is used where needed)."
command -v apt-get >/dev/null || die "This script expects an Ubuntu/Debian image."

# --------------------------------------------------------------- 1. Docker
if ! command -v docker >/dev/null; then
  log "Installing Docker"
  sudo apt-get update -qq
  sudo apt-get install -y -qq ca-certificates curl
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$USER"
  NEEDS_RELOGIN=1
else
  log "Docker already installed: $(docker --version)"
fi

# ------------------------------------------------------- 2. the OS firewall
# Oracle's Ubuntu images ship an iptables REJECT rule that drops everything
# except SSH. Opening ports in the cloud Security List alone is not enough —
# this is the single most common reason an Oracle VM "ignores" port 80/443.
log "Opening ports 80 and 443 in the instance firewall"
if command -v netfilter-persistent >/dev/null || [ -f /etc/iptables/rules.v4 ]; then
  for port in 80 443; do
    if ! sudo iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
      sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport "$port" -j ACCEPT
    fi
  done
  sudo netfilter-persistent save >/dev/null 2>&1 || sudo sh -c 'iptables-save > /etc/iptables/rules.v4'
  echo "  iptables updated and persisted"
else
  echo "  iptables-persistent not present; skipping (check your image's firewall)"
fi
if command -v ufw >/dev/null && sudo ufw status | grep -q "Status: active"; then
  sudo ufw allow 80/tcp >/dev/null && sudo ufw allow 443/tcp >/dev/null
  echo "  ufw rules added"
fi

# --------------------------------------------------------------- 3. swap
# Training peaks above 1 GB. There is plenty of RAM on the A1 shape, but swap
# turns a transient spike into slowness instead of an OOM kill.
if [ "$(swapon --show | wc -l)" -eq 0 ]; then
  log "Adding 4 GB swap"
  sudo fallocate -l 4G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile >/dev/null
  sudo swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
fi

# ----------------------------------------------------------------- 4. .env
if [ ! -f "$ENV_FILE" ]; then
  log "Writing $ENV_FILE"
  PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org || true)"
  [ -n "$PUBLIC_IP" ] || die "Could not determine the public IP; set SITE_ADDRESS manually."
  # sslip.io resolves <dashed-ip>.sslip.io to that IP, so Let's Encrypt can
  # issue a certificate without owning a domain.
  SITE="${PUBLIC_IP//./-}.sslip.io"
  umask 077
  DB_USER=ai
  DB_NAME=ai_data_scientist
  DB_PASS="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/oracle/setup.sh — keep this file private, never commit it.
SITE_ADDRESS=$SITE
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$DB_PASS
POSTGRES_DB=$DB_NAME

# Point this at Neon instead if you prefer a managed database.
DATABASE_URL=postgresql+psycopg2://$DB_USER:$DB_PASS@db:5432/$DB_NAME

# Optional LLM (any OpenAI-compatible endpoint). Empty = built-in local engine.
LLM_API_KEY=
LLM_BASE_URL=https://api.groq.com/openai/v1
LLM_MODEL=openai/gpt-oss-120b

# Set to your Vercel origin once the frontend is deployed.
CORS_ORIGINS=
MAX_UPLOAD_MB=100
EOF
  echo "  SITE_ADDRESS=$SITE"
  echo "  a random database password was generated"
else
  log "Keeping existing $ENV_FILE"
fi

# ----------------------------------------------------------------- 5. up
log "Building and starting (first build takes ~10 minutes on ARM)"
DOCKER="docker"
if [ "${NEEDS_RELOGIN:-0}" = "1" ]; then
  echo "  (using sudo for docker until you log out and back in)"
  DOCKER="sudo docker"
fi
cd "$HERE"
$DOCKER compose up -d --build

log "Waiting for the API"
SITE_ADDRESS="$(grep '^SITE_ADDRESS=' "$ENV_FILE" | cut -d= -f2)"
for _ in $(seq 1 60); do
  if curl -fsS --max-time 5 "http://localhost/api/health" >/dev/null 2>&1; then break; fi
  sleep 5
done

echo
curl -fsS --max-time 10 "https://$SITE_ADDRESS/api/health" \
  && printf '\n\n\033[1;32mBackend is live: https://%s\033[0m\n' "$SITE_ADDRESS" \
  || {
    printf '\n\033[1;33mThe API did not answer over HTTPS yet.\033[0m\n'
    echo "Certificate issuance can take a minute. Check with:"
    echo "  $DOCKER compose -f $HERE/docker-compose.yml logs -f caddy backend"
  }

cat <<EOF

Next:
  1. Vercel -> Environment Variables -> BACKEND_URL = https://$SITE_ADDRESS
  2. Put your LLM key in $ENV_FILE, then: $DOCKER compose -f $HERE/docker-compose.yml up -d
  3. Confirm ports 80/443 are open in the VCN Security List (see deploy/oracle/README.md)
EOF
[ "${NEEDS_RELOGIN:-0}" = "1" ] && echo "
Log out and back in so 'docker' works without sudo."
